import React from 'react';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="page-center">
          <h1>Hello World!</h1>
          <p>This is the Inter font</p>
        </div>
      </main>

      <footer />
    </div>
  );
}
