import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='page-center'>
          <h1>Hello World!</h1>
          <p>This is the Inter font</p>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
// import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
// import Account from '../components/accounts'

// const Home = () => {
//   const session = useSession()
//   const supabase = useSupabaseClient()

//   return (
//     <div className="page-center">
//       {!session ? (
//         <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
//       ) : (
//         <Account session={session}/>
//       )}
//     </div>
//   )
// }

// export default Home
